# Generated by Django 5.1.2 on 2024-11-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='points_earned',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_ops.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'GCash Payment')], default='CASH', max_length=10),
        ),
    ]
