# Generated by Django 5.1.2 on 2024-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0003_employee_date_of_birth_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, help_text='Description of who the supplier is and what they supply', null=True),
        ),
    ]
