# Generated by Django 5.1.2 on 2024-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0004_supplier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
