# Generated by Django 5.1.2 on 2024-12-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0005_purchase_cancelled_purchase_cancelled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store_ops.employee'),
        ),
    ]
