# Generated by Django 5.1.2 on 2024-12-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0006_sale_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'System Default')], default='light', max_length=10)),
                ('time_format', models.CharField(choices=[('24', '24-hour'), ('12', '12-hour')], default='24', max_length=2)),
                ('date_format', models.CharField(choices=[('mdy', 'MM/DD/YYYY'), ('dmy', 'DD/MM/YYYY'), ('ymd', 'YYYY/MM/DD')], default='mdy', max_length=3)),
                ('email_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
