# Generated by Django 5.1.2 on 2024-12-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0007_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount before loyalty points discount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='points_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of loyalty points used for discount', max_digits=12),
        ),
    ]
