# Generated by Django 5.1.2 on 2024-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0008_sale_original_amount_sale_points_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
