# Generated by Django 5.1.2 on 2024-12-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0011_alter_employee_address_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
