# Generated by Django 5.1.3 on 2024-11-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SupplierID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier', to='supplier.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_details', to='inventory.product'),
            preserve_default=False,
        ),
    ]
