# Generated by Django 5.1.1 on 2024-10-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('SaleID', models.AutoField(primary_key=True, serialize=False)),
                ('SaleDate', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('SaleDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentType', models.CharField(max_length=50)),
                ('SaleID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='sales.sale')),
            ],
        ),
    ]
