# Generated by Django 5.1.3 on 2024-11-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '__first__'),
        ('em', '__first__'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='crm.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='em.employee'),
            preserve_default=False,
        ),
    ]
