# Generated by Django 5.1.3 on 2024-11-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_sale_customer_sale_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='inventory.product'),
            preserve_default=False,
        ),
    ]
