# Generated by Django 5.1.3 on 2024-11-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='em.store'),
            preserve_default=False,
        ),
    ]
